version: '3'

services:
  nginx:
    image: 'ghcr.io/tier940/php74:v1.0.1@sha256:c680dc1a7781064da97611729858cea121c40a4e9dbae181d7f2744980e0996f'
    ports:
      - 80:80
    networks:
      - app
    volumes:
      - app-volumes:/var/www/html:delegated
    depends_on:
      - php

  php:
    image: 'ghcr.io/tier940/nginx:v1.0.4@sha256:9358e5f885176182acaa014bb7964f2e6a9f541dd6fb4bade538e94e4a7c0dc4'
    ports:
      - 9000:9000
    volumes:
      - app-volumes:/var/www/html:delegated
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  app-volumes:
    driver: local
