---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
  labels:
    name: app-volume
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: app-volume-claim
  gcePersistentDisk:
    pdName: gke-app-disk
    fsType: ext4
