---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/tier940/nginx:v1.0.1@sha256:79082c74dc2f17fe21a55d08cd126f63e3a6c2bd1f72379cf9764ca17385fe34
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi
          volumeMounts:
            - mountPath: /var/www/html
              name: public
      volumes:
        - name: public
          persistentVolumeClaim:
            claimName: app-volume-claim
