---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: ghcr.io/tier940/php80::v1.0.1@sha256:d02ebfa6a53b1cc03b4eda86863519d84586ff63fe4be65f11eb9c7a520413b1
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi
