apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/app: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: ghcr.io/tier940/php74:v1.0.1@sha256:c680dc1a7781064da97611729858cea121c40a4e9dbae181d7f2744980e0996f
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: app-volumes
      restartPolicy: Always
      volumes:
        - name: app-volumes
          persistentVolumeClaim:
            claimName: app-volumes
status: {}
