---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: ghcr.io/tier940/php74:v1.0.0@sha256:b93e05776283aac89478675837d4d0542efebb5af49cdbd08c0c76fb43b4e6bb
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 5Gi

