---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php74
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php74
  template:
    metadata:
      labels:
        app: php74
    spec:
      containers:
      - name: php74
        image: ghcr.io/tier940/php74:v1.0.0@sha256:b93e05776283aac89478675837d4d0542efebb5af49cdbd08c0c76fb43b4e6bb
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        ports:
        - containerPort: 80
