name: Build and Deploy to GKE

on:
  push:
    branches:
      - 'feature/k8s/*'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_CLUSTER_REGION : ${{ secrets.GKE_CLUSTER_REGION }}
  GKE_CLUSTER_ZONE: ${{ secrets.GKE_CLUSTER_ZONE }}
  GKE_SA: ${{ secrets.GKE_SA }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ env.GKE_SA }}
          project_id: ${{ env.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster region
      - name: Get GKE Clusters
        run: |-
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER_NAME }} --region=${{ env.GKE_CLUSTER_REGION }}

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz
          tar -zxvf kustomize.tar.gz
          chmod u+x ./kustomize

      # Validation Manifests
      - name: Validation
        run: |-
          ./kustomize build ./k8s-apps/web-app | kubectl apply --validate --dry-run -f -

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize build ./k8s-apps/web-app | kubectl apply -f -
          kubectl get services -o wide
