name: Build and Deploy to GitHub Container Registry

on:
  push:
    branches:
      - 'feature/docker/nginx-*'
      - 'feature/docker/php74-*'
      - 'feature/docker/php80-*'

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get docker image info
        run: |
          echo ${GITHUB_REF}
          IMAGE_NAME=$(echo ${GITHUB_REF} | awk -F'/' '{print $5}' | awk -F'-' '{print $1}')
          IMAGE_VERSIN=$(echo ${GITHUB_REF} |awk -F'/' '{print $5}' | awk -F'-' '{print $2}')

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./docker/${IMAGE_NAME}
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ github.repository_owner }}/${IMAGE_NAME}:latest
            ${{ github.repository_owner }}/${IMAGE_NAME}:${IMAGE_VERSIN}
