name: Build and Deploy to GitHub Container Registry

on:
  push:
    branches:
      - 'feature/docker/nginx-*'
      - 'feature/docker/php74-*'
      - 'feature/docker/php80-*'

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_NAME=$(echo ${{ github.head_ref }} | awk -F'/' '{print $3}' | awk -F'-' '{print $1}')
          IMAGE_VERSIN=$(echo ${{ github.head_ref }} |awk -F'/' '{print $3}' | awk -F'-' '{print $2}')

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./docker/$IMAGE_NAME
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
            ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_VERSIN
