name: Build check

on:
  pull_request:
    branches:
      - 'feature/docker/nginx-*'
      - 'feature/docker/php74-*'
      - 'feature/docker/php80-*'
  push:
    branches:
      - 'feature/docker/nginx-*'
      - 'feature/docker/php74-*'
      - 'feature/docker/php80-*'

jobs:
  build:
    name: Setup, Build, and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: get-docker-info
        name: Get docker image info
        run: |-
          IMAGE_NAME=$(echo ${GITHUB_REF} | awk -F'/' '{print $5}' | awk -F'-' '{print $1}')
          IMAGE_VERSIN=$(echo ${GITHUB_REF} | awk -F'/' '{print $5}' | awk -F'-' '{print $2}')
          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
          echo "::set-output name=IMAGE_VERSIN::${IMAGE_VERSIN}"

      - name: Build test docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CONTENT_TRUST: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          # COMPOSE_CONVERT_WINDOWS_PATHS: true
          # COMPOSE_PROJECT_NAME:
        with:
          context: .
          file: ./docker-images/${{ steps.get-docker-info.outputs.IMAGE_NAME }}/Dockerfile
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.get-docker-info.outputs.IMAGE_NAME }}:test
