name: Build check

on:
  pull_request:
    branches:
      - 'nginx-*'
      - 'php74-*'
      - 'php80-*'

jobs:
  build:
    name: Setup, Build, and Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get docker image info
        id: get-docker-info
        run: |-
          IMAGE_NAME=$(echo ${GITHUB_REF} | awk -F'/' '{print $3}' | awk -F'-' '{print $1}')
          IMAGE_VERSIN=$(echo ${GITHUB_REF} | awk -F'/' '{print $3}' | awk -F'-' '{print $2}')
          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
          echo "::set-output name=IMAGE_VERSIN::${IMAGE_VERSIN}"

      - name: Build test docker image
        uses: docker/build-push-action@v2
        with:
          file: ./docker/${{ steps.get-docker-info.outputs.IMAGE_NAME }}/Dockerfile
          load: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.get-docker-info.outputs.IMAGE_NAME }}:test
