name: Lint files

on:
  pull_request:
    branches:
      - 'develop'

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up SuperLinter and Run
      - name: Set up SuperLinter and Run
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKER: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
