name: Lint files

on:
  pull_request:
    branches:
      - 'develop'

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install editorconfig and check
      - name: Install editorconfig and check
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EDITORCONFIG_FILE_NAME: ".editorconfig"
