name: Lint files

on:
  push:
    branches:
      - 'develop'

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install editorconfig and check
      - name: Install editorconfig and check
        run: |-
          npm install -g editorconfig
          filenames=$(git diff --name-only --diff-filter=AM origin/develop)
          if [ -n "$filenames" ]; then
            npm run lint:editorconfig -- "$filenames"
          fi

      # Set up kustomize
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.4.0/kustomize_v4.4.0_linux_amd64.tar.gz
          tar -zxvf kustomize.tar.gz
          chmod u+x ./kustomize

      # Validation Manifests
      - name: Validation
        run: |-
          ./kustomize build . | kubectl apply --validate --dry-run -f -
