name: Lint files

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

env:
  NODE_VERSION: 16

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install editorconfig and check
      - name: Install editorconfig and check
        run: |-
          npm install -g editorconfig
          filenames=$(git diff --name-only --diff-filter=AM origin/develop)
          if [ -n "$filenames" ]; then
            npm run lint:editorconfig -- "$filenames"
          fi
