name: Terraform plan

on:
  pull_request:
    branches:
      - 'feature/terraform/*'
  push:
    branches:
      - 'feature/terraform/*'

env:
  GCP_WORKLOAD_IDENTITY: ${{ secrets.GCP_WORKLOAD_IDENTITY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  test:
    name: Terraform plan
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 1200s

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      # Setup github action only setting
      - name: Setup github action only setting
        run: |-
          cp -prvf ./workflows/* ./

      - name: Terraform Format
        run: |-
          terraform fmt -recursive -check

      - id: init
        name: Terraform Init
        run: |-
          terraform init -reconfigure

      - id: validate
        name: Terraform Validate
        run: |-
          terraform validate -no-color

      - id: plan
        name: Terraform Plan
        continue-on-error: true
        run: |-
          terraform plan -no-color -var-file="env/dev.tfvars"
